name: RDP Setup

on:
  push:
    branches:
      - main

jobs:
  setup-rdp:
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up PowerShell
        uses: microsoft/setup-powershell@v2
        with:
          version: '7.x' # اختر الإصدار المناسب

      - name: Run RDP setup script
        env:
          7047714100:AAHptINe1QLjomnzqKaOMnTm_YRmt5T5XAM: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          242676339: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: |
          pwsh .\setup-rdp.ps1
